containers_folder: containers
composes_folder: composes
network_name: cloud
network_driver: bridge
subnet: 172.20.0.0/24
restart_policy: unless-stopped
use_full_directory: true
bind_path: /home/docker/Docker
output: docker-compose.yaml
